### ISSUE TITLE
Integration problem with django.contrib.auth.models.User

### ISSUE THREAD

**Issue by mbaragiola** [dbkaplan/dry-rest-permissions#20]
Hello, I'm trying to integrate dry-rest-permissions with django.contrib.auth.models.User.

All my custom models have the permissions defined at models.py, but User isn't defined there.

What's the proper way of adding DRY REST permissions to django.contrib.auth.models.User?

Here's the error when I try to access the API:

AssertionError at /api/usuarios/

'<class 'django.contrib.auth.models.User'>' does not have 'has_read_permission' or 'has_list_permission' defined.

Request Method: 	GET
Request URL: 	http://localhost:8000/api/usuarios/
Django Version: 	1.9.2
Exception Type: 	AssertionError
Exception Value: 	

'<class 'django.contrib.auth.models.User'>' does not have 'has_read_permission' or 'has_list_permission' defined.

Exception Location: 	/usr/local/lib/python3.4/site-packages/dry_rest_permissions/generics.py in has_permission, line 123
Python Executable: 	/usr/local/bin/python3.4
Python Version: 	3.4.4
Python Path: 	

['/home/mib/workspace/turnosya',
 '/usr/local/lib/python34.zip',
 '/usr/local/lib/python3.4',
 '/usr/local/lib/python3.4/plat-openbsd5',
 '/usr/local/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/site-packages']

Thanks in advance!

**Comment by dbkaplan** [comment]
Hi Mariano,

There are two ways I know of doing this -- one I have tried and one that I haven't.

There are usually extra fields and methods you want on a user model, so I usually make a new model (called user_profile) that has those extra fields and methods and then has a one to one relationship back to the default user model. Then I point my serializers at user_profile, which will have the permissions methods. This is the standard way to extend user, without rolling your own user model.

Another way you may be able to achieve this -- but I have not tried yet -- is by creating a [proxy model for User](https://docs.djangoproject.com/en/1.9/topics/db/models/#proxy-models). This will allow you to create additional methods and you should be able to point the serializer at that proxy model.

Let me know which one you try.

**Comment by abeniwal** [comment]
I usually create the proxy model for User. I've found it to help avoid a lot of headaches.

@mbaragiola you could also take a look at http://stackoverflow.com/questions/15526858/how-to-extend-a-class-in-python. That might let you extend the User class and add those permissions you're looking for.

**Comment by mbaragiola** [comment]
@dbkaplan @abeniwal 

Thank you for your quick replies.

I also use the extended model feature for adding an user profile. But I happend to make use of the User model for fields such as 'created_by' and 'last_modified_by' because it's easier to write them reading from 'request.user'.

I haven't heard about proxy models before, and I just tested it and works fine that way to add the permissions. I guess the problem is solved. 

If you have further suggestions, I'm all ears. Thanks again!
