### ISSUE TITLE
Field level permissions

### ISSUE THREAD

**Issue by dbinetti** [dbkaplan/dry-rest-permissions#22]
Is there a recommended approach for field-level permissions?

**Comment by dbkaplan** [comment]
Unfortunately, there isn't a generic field level solution at the moment. I had an idea of how I want to get it done, but haven't had the time to implement and there hasn't been a ton of demand for it yet.

**Comment by dbinetti** [comment]
Understood. +1 for this from me. 😀

Also if you want to send me your thoughts on an approach I might run with it for while...

**Comment by jgr3go** [comment]
It might be helpful to list what the use-cases are for this, as this is a little less clear on how to handle generically.  For instance, here are some possible desired workflows:

* Request a record without permission for `x`, return the record, `x` is null (or missing). `HTTP 200` 
* Request a record without permission for `x`, return the record, but `x` is set to some other default or dynamic value to be returned instead. `HTTP 200`
* Request a record without permission for `x`, `HTTP 200` but with custom error
* Request a record without permissions for `x`, `HTTP 403` (can't think of a concrete example of when you'd want this, but it's possible)

* Update a record, attempting to set `x`, `HTTP 403`
* Update a record, attempting to set `x`, updates all except `x`, `HTTP 200`

I don't know, those are off the top of my head.  I can see use-cases for all of them, so whatever this solution is would probably need some additional coding/configuration by the developer to handle these, it might not be as easy to handle completely generically. 

@dbkaplan feel free to correct me, but knowing @dbinetti 's use case could help getd a head start.

**Comment by dbinetti** [comment]
Concretely:

- Say you have a contest including a number of competitors. The competitors are scored, privately, by a panel of judges. Those scores need to be persisted to each Competitor model and used for all sorts of other processing (ranking, for instance). These private data should be accessible to the judges, or admins, or other authorized users, but not to the public at large. However, we do want to have the Competitor name and other details made available.

Now I could create other models (and have, frankly) to handle this. However, it would be useful to have a field like `rank` which is permissions-enabled to allow the use case I described above.

I might be running afoul of REST here, since the use case is more on the serializer (`rank`= INT for authorized, `rank`=None for unauthorized) but anyway that's the use case....

**Comment by dbinetti** [comment]
I came up with a solution: the fields in question are essentially denormalizations, so I've simply made them into functions which I can protect as actions.  It's a bit more expensive, but it works.

**Comment by jordanmkoncz** [comment]
@dbinetti Any chance you could provide some code samples and/or more detail for how you solved this?

**Comment by dbinetti** [comment]
as it turns out, making them into functions didn't work; i eventually just created two model serializations: one with public fields, and one with private fields.  i then adjusted permissions accordingly.

this solution (multiple serializations) is probably the best approach even if doesn't seem the DRYest since it keeps the cleanest separation between public/private

**Comment by jordanmkoncz** [comment]
@dbinetti Fair enough, what technique are you using in order to use a different serializer depending on permissions? Does this technique work with nested serializers?

**Comment by dbinetti** [comment]
I'm not doing any switching, because I am not overlapping the fields. The public model gets the public fields, the private model gets the private fields. The fields are mutually exclusive. I then just check permissions normally. It means that you need to think about your UI in terms of the public and private components.

I have no experience with nested serializers and can't answer that.
