### ISSUE TITLE
Model level permissions in Meta

### ISSUE THREAD

**Issue by dbinetti** [dbkaplan/dry-rest-permissions#34]
Using DRYP I can't determine the best way to check model-level permissions through a Django Rest Framework API if I don't have an object available.

This is the use-case:  I'd like to present a UI element only if the user has create permissions.  However, if I have yet to create the object then there's nothing to check.  True, the create permissions will eventually do the right thing but I don't want to show the `New` button at all if it's not possible.  I know how to do this the conventional way; how does one do it with DRYP?  thanks....

**Comment by dbinetti** [comment]
ping

**Comment by auvipy** [comment]
I am going to vendor this project on my maintain drf-extensions packge. will go through the issues and merge some open pr there.
