### ISSUE TITLE
Wrong permission being checked on Create/POST.

### ISSUE THREAD

**Issue by DDevine** [dbkaplan/dry-rest-permissions#35]
I am having the problem described in #29 however that was closed without a discussion or solution.
```python
class FooDeviceViewSet(viewsets.ModelViewSet):
    """CRUD for Foo Devices.""
    model = FooDevice
    serializer_class = FooDeviceSerializer
    filter_backends = (DomainFilterBackend,)
    permission_classes = (DRYObjectPermissions,)
    queryset = FooDevice.objects.all()
```
The FooDevice permissions in models.py are:
```python
    def has_object_read_permission(self, request):
        """You can read a FooDevice if you are in the Domain, or superuser."""
        if request.user.is_superuser: 
            return True
        else:
            for users in [dom.get_users() for dom in self.domains.all()]:
                if users.filter(id=request.user.id).count() > 0:
                    return True
            return False

    def has_object_write_permission(self, request):
        """Only superusers can create/write devices."""
        return request.user.is_superuser
```
And here's how I know that I am hitting the intended URL and the wrong thing is happening.
```python
    def test_unauthorised_dali_device_create(self):
        """Create a Foo Device"""
        url = reverse("my_api:foo_device-list")
        dev_data = {"description": "test device", "dev_id": 0xA, "controller": self.controller.id, "domains": [self.domain.id,],}
        response = self.client.post(self.url, dev_data, format='json')
        self.assertTrue(response.status_code == 403, "(HTTP %s) %s" % (response.status_code, response.content.decode()))
```
Which results in:
```
AssertionError: False is not true : (HTTP 201) {"id":8,"description":"test device", domains":[1]}
```
When you call create on a list URL it seems to call "has_object_read_permission" rather than "has_object_write_permission" (according to print statements inserted in has_object_read_permission)

When checking request.method in generics.py it appears as though it is recieving a GET request which would obviously cause the _read_permission to be run... The question is, where is the GET request coming into the stack?

**Comment by mbaragiola** [comment]
```
from dry_rest_permissions.generics import authenticated_users, allow_staff_or_superuser

@authenticated_users
@allow_staff_or_superuser
def has_object_read_permission(self, request):
        """You can read a FooDevice if you are in the Domain, or superuser."""
        for users in [dom.get_users() for dom in self.domains.all()]:
            if users.filter(id=request.user.id).count() > 0:
                return True
         return False

    @authenticated_users
    @allow_staff_or_superuser
    def has_object_write_permission(self, request):
        """Only superusers can create/write devices."""
        return False
´´´

How are you handling views? Here's a small example of how I do:

```
class GymnasiumHasUserViewSet(RetrieveCacheResponseMixin, RetrieveViewSet):
    permission_classes = (DRYPermissions,)
    queryset = models.GymnasiumHasUser.objects.all()
    serializer_class = serializers.GymnasiumHasUserSerializer

    @transaction.atomic
    @detail_route(methods=['patch'], url_path='disable')
    def disable(self, request, pk=None):
        if pk is not None:
            gym_has_user = models.GymnasiumHasUser.objects.filter(
                pk=pk,
                is_active=True,
                gymnasium__is_active=True
            )
            if gym_has_user.exists():
                gym_has_user = gym_has_user.first()
                self.check_object_permissions(request, gym_has_user)
                if gym_has_user.user_profile != request.user.user_profile:
                    gym_has_user.is_active = False
                    if gym_has_user.is_staff:
                        gym_has_user.user_profile.user_category -= 1
                        gym_has_user.user_profile.save(force_update=True)
                    gym_has_user.last_modified_by = request.user.user_profile
                    gym_has_user.save()
                    serializer = serializers.GymnasiumHasUserSerializer(
                        gym_has_user,
                        context={'request': request}
                    )
                    return Response(serializer.data, status.HTTP_200_OK)

        return Response({}, status.HTTP_400_BAD_REQUEST)

class UsersByGymnasiumList(ListCacheResponseMixin, ListCreateAPIView):
    permission_classes = (DRYPermissions,)
    serializer_class = serializers.GymnasiumHasUserSerializer
    filter_class = GymnasiumHasUserFilter

    def get_queryset(self):
        gymnasium_pk = self.kwargs['pk']
        queryset = models.GymnasiumHasUser.objects.filter(
            gymnasium=gymnasium_pk
        )
        gymnasium = models.Gymnasium.objects.filter(pk=gymnasium_pk)
        user = self.request.user
        if gymnasium.exists():
            is_gym_staff = gymnasium.first().has_staff(user.user_profile)
            if is_gym_staff or user.is_staff or user.is_superuser:
                return queryset
            else:
                return queryset.filter(user_profile__user=user)

        return queryset.none()
```

Hope it helps.

**Comment by DDevine** [comment]
The issue I am going to chase down today is why a GET request is coming in rather than a POST and hitting has_object_read_permission rather than has_object_write_permission - this may not be a DRY Permissions issue yet because I don't think DRY Permissions does any altering of request.method. I suspect it is an issue with DRF APIClient.

If I were to take your approach there would actually be no point at all using DRY Permissions at all because all the permissions handling would be done in get_queryset() and the views, which is what DRY Permissions is trying to avoid - "Don't Repeat Yourself".

**Comment by DDevine** [comment]
See #18 for what the root of the issue is.

(Essentially, to secure Create you must have a **global permission** on the model **in addition to** an object permission for write - and use `DRYPermissions` rather than just `DRYObjectPermissions`.)
